version: "3.8"
services:
    db:
        ports:
            - "3306:3306"
        volumes:
            - ./docker/data:/var/lib/mysql/data
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=username
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=dbname
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
    back-end:
        ports:
            - "9090:9090"
        volumes:
            - ./:/usr/src/app
    front-end:
        ports:
            - "80:3000"
        volumes:
            - ./:/usr/src/app
        environment:
            - NODE_ENV=development
            - CHOCIDAR_USEPOLLING=true
