version: "3.8"
services:
    db:
        image: mysql:8.0.20
        container_name: kpscoj-db
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
    back-end:
        container_name: kpscoj-back-end
        build:
            context: ./back-end
            dockerfile: Dockerfile.dev
        depends_on:
            - "db"
        command: bash -c "./wait-for-it.sh db:3306 -t 30 && yarn start"
    front-end:
        container_name: kpscoj-front-end
        build:
            context: ./front-end
            dockerfile: Dockerfile.dev
        stdin_open: true
